ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
        baseUrl: "http://localhost:8080"
        uselessFactApiUrl: "https://uselessfacts.jsph.pl/random.json?language=en"
        apiKey: "testing-only"
    deployment:
        port: 8080
